# USER PRODUCT REVIEW
subgraphs:
  user:
    routing_url: http://localhost:4001/user
    schema:
      file: src/subgraphs/user.graphql
  product:
    routing_url: http://localhost:4001/product
    schema:
      file: src/subgraphs/product.graphql
  review:
    routing_url: http://localhost:4002/review
    schema:
      file: src/subgraphs/review.graphql
